# Generated by Django 5.2.6 on 2025-10-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_panel', '0002_utilisateur_adresse_utilisateur_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emploitemps',
            old_name='matiere',
            new_name='logiciel',
        ),
        migrations.RenameField(
            model_name='etudiant',
            old_name='code_eleve',
            new_name='matricule',
        ),
        migrations.RenameField(
            model_name='inscription',
            old_name='eleve',
            new_name='etudiant',
        ),
        migrations.RenameField(
            model_name='logiciel',
            old_name='duree_heures',
            new_name='duree_jours',
        ),
        migrations.RemoveField(
            model_name='logiciel',
            name='enseignant',
        ),
        migrations.AddField(
            model_name='logiciel',
            name='duree',
            field=models.CharField(choices=[('1semaine', '1 semaine'), ('2semaines', '2 semaines'), ('3semaines', '3 semaines'), ('1mois', '1 mois'), ('2mois', '2 mois'), ('3mois', '3 mois'), ('indefini', 'Indéfini')], default='indefini', max_length=20),
        ),
        migrations.AddField(
            model_name='logiciel',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='logiciel',
            name='code_logiciel',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('etudiant', 'logiciel')},
        ),
    ]
