# Generated by Django 5.2.6 on 2025-10-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_panel', '0003_rename_matiere_emploitemps_logiciel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='prix_inscription',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
