# Generated by Django 5.2.5 on 2025-12-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_panel', '0005_alter_inscription_etudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='extrait_naissance',
            field=models.FileField(blank=True, null=True, upload_to='extraits_naissance/'),
        ),
    ]
